server:
    address: 116.204.9.108
    port: 12321

spring:
  datasource:
    url: jdbc:mysql://116.204.9.108:3306/emoprobe?serverTimezone=GMT%2B8
    username: minjer
    password: d3nCxeWC8ZBCShtF
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.minjer.mapper: DEBUG
